import React, { useState } from 'react';
import {
  Server,
  Database,
  Code2,
  Table,
  Cpu,
  ArrowRight,
  Shield,
  Layers,
  Copy,
  Check,
} from 'lucide-react';

export const BackendArchitectureView: React.FC = () => {
  const [activeTab, setActiveTab] = useState<'endpoints' | 'schema' | 'fastapi_code'>('endpoints');
  const [copied, setCopied] = useState(false);

  const endpoints = [
    {
      method: 'GET',
      path: '/api/v1/buses',
      desc: 'List active roadway buses with status filter, depot, and multi-city query parameters.',
      badge: 'bg-emerald-950 text-emerald-400 border-emerald-800',
    },
    {
      method: 'GET',
      path: '/api/v1/buses/{bus_id}/live',
      desc: 'Real-time telemetry, current speed, GPS lat/lng, next stop ETA, and active delay risk.',
      badge: 'bg-emerald-950 text-emerald-400 border-emerald-800',
    },
    {
      method: 'POST',
      path: '/api/v1/predict/delay',
      desc: 'Run multi-target AI delay inference model using speed, corridor density, and time of day.',
      badge: 'bg-blue-950 text-blue-400 border-blue-800',
    },
    {
      method: 'POST',
      path: '/api/v1/hardware/telemetry',
      desc: 'Ingest 1Hz AIS-140 / ESP32 MQTT NMEA payloads from onboard GPS hardware.',
      badge: 'bg-blue-950 text-blue-400 border-blue-800',
    },
    {
      method: 'GET',
      path: '/api/v1/alerts',
      desc: 'Fetch automated passenger and driver advisory alerts generated by sensor fusion.',
      badge: 'bg-emerald-950 text-emerald-400 border-emerald-800',
    },
    {
      method: 'GET',
      path: '/api/v1/heatmap',
      desc: 'Corridor-level traffic congestion scores and bottleneck indexes across metropolitan corridors.',
      badge: 'bg-emerald-950 text-emerald-400 border-emerald-800',
    },
  ];

  const sqlSchema = `-- ==========================================================
-- TransitPulse AI PostgreSQL Production Database Schema
-- Optimized for High-Frequency AIS-140 GPS Telemetry & AI Inference
-- ==========================================================

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "postgis"; -- Geospatial routing support

-- 1. Bus Details
CREATE TABLE buses (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    bus_number VARCHAR(32) UNIQUE NOT NULL,      -- e.g. 'UPSRTC-204'
    operator VARCHAR(64) NOT NULL DEFAULT 'UPSRTC',
    depot_city VARCHAR(64) NOT NULL,
    capacity INT DEFAULT 52,
    active_route_id VARCHAR(64),
    driver_name VARCHAR(128),
    driver_phone VARCHAR(32),
    hardware_imei VARCHAR(64) UNIQUE,
    is_in_service BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Routes & Designated Corridors
CREATE TABLE routes (
    id VARCHAR(64) PRIMARY KEY,                  -- e.g. 'UP-MEERUT-GZB'
    route_name VARCHAR(128) NOT NULL,
    source_city VARCHAR(64) NOT NULL,
    destination_city VARCHAR(64) NOT NULL,
    total_distance_km NUMERIC(6, 2) NOT NULL,
    standard_duration_minutes INT NOT NULL,
    corridor_geometry GEOMETRY(LineString, 4326),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. High-Frequency GPS Logs (TimescaleDB / Hypertable ready)
CREATE TABLE gps_telemetry_logs (
    id BIGSERIAL PRIMARY KEY,
    bus_id UUID REFERENCES buses(id) ON DELETE CASCADE,
    latitude NUMERIC(9, 6) NOT NULL,
    longitude NUMERIC(9, 6) NOT NULL,
    speed_kmh NUMERIC(5, 2) NOT NULL,
    heading_degrees INT,
    hdop NUMERIC(3, 1),
    satellites_count INT DEFAULT 10,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE INDEX idx_gps_bus_time ON gps_telemetry_logs(bus_id, timestamp DESC);

-- 4. Traffic Density & Roadway Bottlenecks
CREATE TABLE corridor_traffic_data (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    route_id VARCHAR(64) REFERENCES routes(id),
    corridor_segment VARCHAR(128) NOT NULL,      -- e.g. 'Modinagar Flyover'
    traffic_density_percent INT NOT NULL,        -- 0 to 100
    average_flow_speed_kmh NUMERIC(5, 2) NOT NULL,
    congestion_index NUMERIC(3, 2) NOT NULL,     -- 0.00 to 1.00
    reported_incident VARCHAR(128),
    recorded_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. AI Delay Predictions
CREATE TABLE delay_predictions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    bus_id UUID REFERENCES buses(id) ON DELETE CASCADE,
    delay_probability_percent INT NOT NULL,      -- e.g. 78
    predicted_delay_minutes INT NOT NULL,        -- e.g. +14
    risk_score NUMERIC(3, 1) NOT NULL,           -- e.g. 8.2
    risk_level VARCHAR(16) NOT NULL,             -- 'low','medium','high','critical'
    reason_summary TEXT,
    dynamic_eta_timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
    model_version VARCHAR(32) DEFAULT 'ensemble_v2.4',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 6. Passenger & Authority Alerts
CREATE TABLE transit_alerts (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    bus_id UUID REFERENCES buses(id) ON DELETE SET NULL,
    city VARCHAR(64) NOT NULL,
    alert_type VARCHAR(32) NOT NULL,             -- 'traffic_delay','accident','road_blockage'
    severity VARCHAR(16) NOT NULL,               -- 'info','warning','critical'
    title VARCHAR(128) NOT NULL,
    message TEXT NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);`;

  const fastApiCode = `from fastapi import FastAPI, HTTPException, Depends
from pydantic import BaseModel
from typing import List, Optional
import uvicorn
import joblib
import numpy as np

app = FastAPI(
    title="TransitPulse AI API",
    description="Intelligent Public Transit Delay Prediction & Telemetry Engine",
    version="1.0.0"
)

# Load Scikit-Learn Model
model = joblib.load("models/delay_predictor_rf.pkl")

class TelemetryPacket(BaseModel):
    imei: str
    bus_number: str
    latitude: float
    longitude: float
    speed: float
    heading: int
    hdop: float

class PredictionRequest(BaseModel):
    bus_speed_kmh: float
    speed_limit_kmh: float
    traffic_density_percent: int
    historical_congestion_index: float
    time_of_day_hours: int
    remaining_distance_km: float

@app.post("/api/v1/predict/delay")
async def predict_delay(req: PredictionRequest):
    features = np.array([[
        req.bus_speed_kmh,
        req.speed_limit_kmh,
        req.traffic_density_percent,
        req.historical_congestion_index,
        req.time_of_day_hours,
        req.remaining_distance_km
    ]])
    
    predicted_delay = float(model.predict(features)[0])
    prob = min(98, max(5, int((req.traffic_density_percent * 0.6) + (predicted_delay * 2.5))))
    risk_score = round(min(10.0, max(0.5, (prob / 10.0))), 1)
    
    risk_level = "critical" if risk_score > 8.5 else "high" if risk_score > 6.5 else "medium" if risk_score > 4.0 else "low"

    return {
        "predicted_delay_minutes": max(0, int(round(predicted_delay))),
        "delay_probability_percent": prob,
        "risk_score": risk_score,
        "risk_level": risk_level,
        "status": "success"
    }

@app.post("/api/v1/hardware/telemetry")
async def ingest_telemetry(pkt: TelemetryPacket):
    # Ingest AIS-140 GPS ping and write to TimescaleDB
    return {"status": "acknowledged", "bus": pkt.bus_number}
`;

  return (
    <div className="space-y-8 pb-16">
      {/* Header */}
      <section className="bg-gradient-to-r from-slate-900 via-slate-900/95 to-slate-950 border border-slate-800 rounded-3xl p-6 sm:p-8 shadow-xl">
        <div className="max-w-3xl">
          <div className="inline-flex items-center gap-2 bg-purple-950/80 border border-purple-800/60 px-3 py-1 rounded-full text-xs font-semibold text-purple-400 mb-3">
            <Server className="w-3.5 h-3.5" />
            <span>FastAPI & PostgreSQL Ready</span>
          </div>
          <h2 className="text-2xl sm:text-3xl font-black text-white tracking-tight">
            Backend Architecture & Database Spec
          </h2>
          <p className="text-sm text-slate-300 mt-2 leading-relaxed">
            Enterprise-grade cloud backend structure architected with FastAPI microservices and PostgreSQL
            relational schemas with PostGIS geospatial indexing for state transport corporations.
          </p>

          <div className="flex items-center gap-2 mt-5">
            <button
              onClick={() => setActiveTab('endpoints')}
              className={`px-3.5 py-1.5 rounded-xl text-xs font-semibold transition-all ${
                activeTab === 'endpoints'
                  ? 'bg-cyan-500 text-slate-950 font-bold shadow-md'
                  : 'bg-slate-800 text-slate-300 hover:bg-slate-750'
              }`}
            >
              FastAPI REST Endpoints
            </button>
            <button
              onClick={() => setActiveTab('schema')}
              className={`px-3.5 py-1.5 rounded-xl text-xs font-semibold transition-all ${
                activeTab === 'schema'
                  ? 'bg-cyan-500 text-slate-950 font-bold shadow-md'
                  : 'bg-slate-800 text-slate-300 hover:bg-slate-750'
              }`}
            >
              PostgreSQL Relational Schema
            </button>
            <button
              onClick={() => setActiveTab('fastapi_code')}
              className={`px-3.5 py-1.5 rounded-xl text-xs font-semibold transition-all ${
                activeTab === 'fastapi_code'
                  ? 'bg-cyan-500 text-slate-950 font-bold shadow-md'
                  : 'bg-slate-800 text-slate-300 hover:bg-slate-750'
              }`}
            >
              Python Server Entrypoint
            </button>
          </div>
        </div>
      </section>

      {/* Tab: Endpoints */}
      {activeTab === 'endpoints' && (
        <section className="space-y-4">
          <div className="flex items-center justify-between">
            <h3 className="text-base font-bold text-white">Production REST API Specification</h3>
            <span className="text-xs font-mono text-cyan-400 bg-slate-900 border border-slate-800 px-3 py-1 rounded-xl">
              Swagger / OpenAPI 3.1 Ready
            </span>
          </div>

          <div className="grid grid-cols-1 gap-3">
            {endpoints.map((ep, i) => (
              <div
                key={i}
                className="bg-slate-900/80 border border-slate-800 rounded-2xl p-4 sm:p-5 flex flex-col sm:flex-row sm:items-center justify-between gap-4 hover:border-slate-700 transition-colors"
              >
                <div className="space-y-1">
                  <div className="flex items-center gap-2">
                    <span className={`px-2.5 py-0.5 rounded-md font-mono text-xs font-bold border ${ep.badge}`}>
                      {ep.method}
                    </span>
                    <span className="font-mono text-sm font-bold text-white">{ep.path}</span>
                  </div>
                  <p className="text-xs text-slate-400 pl-0.5">{ep.desc}</p>
                </div>
                <div className="flex items-center gap-2">
                  <span className="text-[11px] font-mono text-emerald-400 bg-slate-950 px-2.5 py-1 rounded-lg border border-slate-800">
                    200 OK
                  </span>
                </div>
              </div>
            ))}
          </div>
        </section>
      )}

      {/* Tab: SQL Schema */}
      {activeTab === 'schema' && (
        <section className="bg-slate-900/80 border border-slate-800 rounded-3xl p-6 sm:p-8 space-y-4 shadow-xl">
          <div className="flex items-center justify-between">
            <div>
              <h3 className="text-base font-bold text-white">PostgreSQL Data Model</h3>
              <p className="text-xs text-slate-400">
                Tables: <code>buses</code>, <code>routes</code>, <code>gps_telemetry_logs</code>, <code>corridor_traffic_data</code>, <code>delay_predictions</code>, <code>transit_alerts</code>
              </p>
            </div>
            <button
              onClick={() => {
                navigator.clipboard.writeText(sqlSchema);
                setCopied(true);
                setTimeout(() => setCopied(false), 2000);
              }}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-slate-800 text-slate-300 hover:text-white text-xs border border-slate-700"
            >
              {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
              <span>{copied ? 'Copied' : 'Copy SQL'}</span>
            </button>
          </div>

          <pre className="p-4 bg-slate-950 rounded-2xl border border-slate-800 text-xs font-mono text-emerald-400 overflow-x-auto leading-relaxed shadow-inner">
            {sqlSchema}
          </pre>
        </section>
      )}

      {/* Tab: FastAPI Code */}
      {activeTab === 'fastapi_code' && (
        <section className="bg-slate-900/80 border border-slate-800 rounded-3xl p-6 sm:p-8 space-y-4 shadow-xl">
          <div className="flex items-center justify-between">
            <div>
              <h3 className="text-base font-bold text-white">FastAPI Model Microservice (main.py)</h3>
              <p className="text-xs text-slate-400">Production-ready async Python endpoint definition</p>
            </div>
          </div>

          <pre className="p-4 bg-slate-950 rounded-2xl border border-slate-800 text-xs font-mono text-cyan-300 overflow-x-auto leading-relaxed shadow-inner">
            {fastApiCode}
          </pre>
        </section>
      )}
    </div>
  );
};
